name: trenstop
description: Excluzeev

version: 1.0.22+25

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^0.3.1+1
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.4.3
  timeago: ^2.0.8
  device_info: ^0.3.0
  rxdart: ^0.20.0
  rounded_modal: ^1.0.0
  flutter_advanced_networkimage: ^0.5.0-alpha.3
  flutter_cache_manager: any
  flutter_native_image:
    git: https://github.com/btastic/flutter_native_image.git
  firebase_messaging: ^4.0.0+1
  firebase_analytics: ^2.0.2+1
  firebase_storage: ^2.1.0
  image_picker: 0.5.0+3
  image_cropper: ^1.0.0
  firebase_auth: ^0.8.1+3
  uuid: any
  cloud_firestore: ^0.9.5+1
  firestore_ui: ^1.1.1
  crypto: ^2.0.6
  # custom_chewie: ^0.7.0
  http: ^0.12.0+1
  permission_handler: ^2.1.2
  flutter_webview_plugin:
    path: plugins/flutter_webview
  flutter_rtmp_publisher:
    path: plugins/flutter_rtmp_publisher
  flutter_search_bar:
    path: plugins/flutter_search_bar
  stripeelements:
    path: plugins/stripeelements
  # flutter_search_bar: any
  screen: ^0.0.5
  flutter_custom_tabs: ^0.6.0
  fluttertoast: ^3.0.3
  firebase_remote_config: ^0.1.0+2
  chewie: ^0.9.7

  built_collection: ">=2.0.0 <5.0.0"
  built_value: ">=5.5.5 <7.0.0"

dependency_overrides:
  video_player: ^0.10.0+4

# flutter packages pub run build_runner build
dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator: ^6.5.0
  pedantic: ^1.4.0
  quiver: ">=0.21.0 <3.0.0"
  intl: any
  intl_translation: any
  flutter_launcher_icons: any

# flutter packages pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: "ic_launcher"
  image_path: "res/icons/logo/logo.png"

flutter:
  uses-material-design: true

  assets:
    - res/icons/logo/
    - res/
    - res/icons/

  fonts:
    #  - family: AppIcon
    #    fonts:
    #    - asset: res/fonts/AppIcon.ttf
    - family: Quicksand
      fonts:
        - asset: res/fonts/Quicksand-Regular.ttf
        - asset: res/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: res/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: res/fonts/Quicksand-Bold.ttf
          weight: 700
# flutter build apk --release --target-platform android-arm
